linters-settings:
  govet:
    # removed "check-shadowing" (use shadow linter instead)
    # you can keep other govet settings here if needed
  staticcheck:
    checks: ["all"]

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    - govet
    - staticcheck
    - shadow   # replaces the old govet.check-shadowing
    - gofumpt
    - gosimple
    - errcheck
    - ineffassign