linters-settings:
  staticcheck:
    checks: ["all"]

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - gofumpt
    - gosimple
    - errcheck
    - ineffassign